version: '2'
services:
    app:
        image: krompi/base
        volumes:
            - /srv/sti/www:/srv
        restart: always
    php:
        image: krompi/php5
        container_name: container-krompi-php
        environment:
          - HTTP_PROXY="10.167.16.21:80"
          - HTTPS_PROXY="10.167.16.21:80"
        links:
          - mysql:db_mysql
          - postgres:db_postgres
        ports:
            - "4000:4000"
            #- "8000:8000"
            - "9000:9000"
        volumes_from:
            - app
        restart: always
    apache:
        image: krompi/apache
        container_name: container-krompi-apache
        links:
          - php
        ports:
            - "80:80"
            - "443:443"
        volumes_from:
            - app
        volumes:
            - ../apache-own-default.conf:/etc/apache2/sites-enabled/own-default.conf
        restart: always
    postgres:
        image: krompi/postgres
        container_name: container-krompi-postgres
        ports:
            - "5432:5432"
        volumes:
            - /srv/sti/postgresdata:/var/lib/postgresql
        restart: always
    mysql:
        image: mysql:latest
        container_name: container-krompi-mysql
        environment:
            - MYSQL_ROOT_PASSWORD=test
            - MYSQL_USER=sti
            - MYSQL_PASSWORD=test
            - MYSQL_DATABASE=sti
        ports:
            - "3306:3306"
        volumes:
            - /srv/sti/mysql:/var/lib/mysql
            - ../mysql-own.cnf:/etc/mysql/conf.d/mysql-own.cnf
        restart: always
    myadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: container-krompi-myadmin
        links:
          - mysql:db
        ports:
            - "8080:80"
        restart: always
