version: '2'
#volumes:
#    postgresdata: {}
#    www: {}
services:
#    app:
#        image: krompi/base
#        volumes:
#            #- /home/krompi/Docker/Krompi/compose/www:/var/www/html
#            - /srv/docker/www:/var/www/html
    php:
        image: php:5.6-apache
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /srv/docker/www:/var/www/html
#    apache:
#        image: httpd:2.4
#        ports:
#            - "80:80"
#            - "443:443"
#        volumes:
#            - /srv/docker/www:/var/www/html
    maria-db:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: test-test
            MYSQL_USER: krompi
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test-test
            MYSQL_DATABASE: krompi
        ports:
            - "3306:3306"
        volumes:
            - /srv/docker/mariadb:/var/lib/mysql